services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "5672:5672"
      - "15672:15672"

  pika-client:
    build: ./app
    container_name: pika-client
    depends_on:
      - rabbitmq

