services:
  node1:
    image: rabbitmq:management
    hostname: node1
    container_name: node1
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq  # A shared secret for clustering
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15671:15672"  # RabbitMQ management UI for node 1
      - "5671:5672"    # AMQP protocol
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
                  # mount host folder to data directory (Raft logs, message store, Mnesia)
      - ./data/node1:/var/lib/rabbitmq
    networks:
      - rabbitmq-net



  node2:
    image: rabbitmq:management
    hostname: node2
    container_name: node2
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq  # Same cookie for all nodes
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15672:15672"  # RabbitMQ management UI for node 2
      - "5672:5672"    # AMQP protocol
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
                  # mount host folder to data directory (Raft logs, message store, Mnesia)
      - ./data/node2:/var/lib/rabbitmq
    networks:
      - rabbitmq-net
    depends_on:
      - node1

  node3:
    image: rabbitmq:management
    hostname: node3
    container_name: node3
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq # Same cookie for all nodes
      - RABBITMQ_DEFAULT_USER=admin        # Set the default username
      - RABBITMQ_DEFAULT_PASS=password    # Set the default password
    ports:
      - "15673:15672"  # RabbitMQ management UI for node 3
      - "5673:5672"    # AMQP protocol
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
                  # mount host folder to data directory (Raft logs, message store, Mnesia)
      - ./data/node3:/var/lib/rabbitmq
    networks:
      - rabbitmq-net
    depends_on:
      - node2

  haproxy:
    image: haproxy
    hostname: haproxy
    container_name: haproxy
    ports:
      - "9000:9000" # management UI
      - "8888:8888" # port for rabbitmq amqp connection
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - rabbitmq-net
    depends_on:
      - node3

  grale-client:
    image: gradle
    hostname: gradle-client
    container_name: gradle-client
    working_dir: /project
    tty: true
    stdin_open: true
    volumes:
      - ./gradle-client:/project
    command: ["/bin/bash"]
    networks:
      - rabbitmq-net


  maven-client:
    image: maven
    container_name: maven-client
    hostname: maven-client
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - ./maven-client:/app
    command: bash   # <-- stay in bash, do NOT run mvn
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge

